version: "3"
services:
    webserver:
        image: webserver
        container_name: webserver
        build:
            context: .
            dockerfile: docker/Dockerfile
        env_file:
            - docker/.docker.env
        environment:
            CONTAINER_ROLE: app
            XDEBUG_CONFIG: remote_host=host.docker.internal
        depends_on:
            - mysql-server
        links:
            - mysql-server
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
    mysql-server:
        image: mysql-server
        container_name: mysql-server
        build:
            context: .
            dockerfile: docker/MySQLDockerfile
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: weintegral
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "33061:3306"
volumes:
    mysql_data:
        driver: "local"
